### ISSUE TITLE
fix treeStableTimer use in build scheduler

### ISSUE THREAD

**Issue by ramcq** [flathub/buildbot-config#12]
http://docs.buildbot.net/current/manual/cfg-schedulers.html#singlebranchscheduler
> The behavior of this scheduler is undefined, if treeStableTimer is set, and changes from multiple branches, repositories or codebases are accepted by the filter.

I suspect what will happen in practice is that if pushes are made to two repos during the same timer window, only one will actually get built.

However, with no treeStableTimer, a push with multiple patches in results in multiple builds, which is even less desirable.

This is a consequence of using a single scheduler for multiple repositories, but because the repositories we're willing to build changes dynamically, I'm not sure how to handle this.

**Comment by alexlarsson** [comment]
We now use a AnyBranchScheduler, which should make the tree stable timer ok.
