### ISSUE TITLE
Add QGnomePlatform

### ISSUE THREAD

**Issue by nedrichards** [flathub/buildbot-config#24]
KDE apps are somewhat deficient on GNOME-y Linux desktops without the org.kde.PlatformTheme.QGnomePlatform extension. This is hosted in the '[flatpak-kde-applications](https://github.com/KDE/flatpak-kde-applications)' repo rather than the main KDE runtimes repo.

Should we add this as an 'autobuild' target like [the KDE SDK](https://github.com/flathub/buildbot-config/blob/184d4944ac17880b1936570e5f51c711851aa37e/builds.json#L16) or add in another way?

Also, do we need the KStyle extensions in the linked repo? @jgrulich @aleixpol as KDE experts may be able to help on that.

**Comment by aleixpol** [comment]
Hey,
Yes, it probably would make sense to have it in fl
athub as well. The only reason why we didn't move it was that one can only have 1 package per repository.

**Comment by TingPing** [comment]
@aleixpol On a related note I'd love if we could get them auto-installing like the Gtk themes do

**Comment by aleixpol** [comment]
Sure, patches very welcome.

**Comment by TingPing** [comment]
@aleixpol I just need to know how to determine the Qt theme and if the GNOME platform should be installed.

**Comment by aleixpol** [comment]
https://cgit.kde.org/flatpak-kde-applications.git/tree/org.kde.PlatformTheme.QGnomePlatform.json

Qt platform needs to be present when `XDG_CURRENT_DESKTOP=Gnome`

**Comment by TingPing** [comment]
Cool, do any other platforms exist that might be packaged in the future? And again how are Qt themes set?

**Comment by aleixpol** [comment]
> Cool, do any other platforms exist that might be packaged in the future?
I don't know.

> And again how are Qt themes set?
They're installed in lib/plugins/styles/

**Comment by aleixpol** [comment]
@grulja may be able to help

**Comment by grulja** [comment]
QGnomePlatform should be installed for Gnome, which means when XDG_CURRENT_DESKTOP contains "GNOME" (it can be also "GNOME-classic") and this platform plugin is used automatically when present. For Qt themes it's also pretty simple, they are loaded/selected by QGnomePlatform so when QGnomePlatform detects the user uses Adwaita gtk theme, then it will load Adwaita-qt theme for Qt apps. Note that besides Adwaita theme, there is also Highcontrast-qt theme.

**Comment by TingPing** [comment]
> For Qt themes it's also pretty simple, they are loaded/selected by QGnomePlatform so when QGnomePlatform detects the user uses Adwaita gtk theme, then it will load Adwaita-qt theme for Qt apps. 

Is the KStyle extension point *only* for matching gtk themes then?

**Comment by grulja** [comment]
It's not only for gtk themes, it's for any Qt theme.

**Comment by TingPing** [comment]
> It's not only for gtk themes, it's for any Qt theme.

So how do we determine the active Qt theme?

Oh and do you not accept PRs here? https://github.com/KDE/flatpak-kde-runtime/pull/3

**Comment by grulja** [comment]
Well, I can't think of any proper way. Qt themes are usually set by platform theme. Only solution I can think of is to read ~/.config/kdeglobals, but that's a KDE specific way. @aleixpol do you have any other idea?

**Comment by TingPing** [comment]
Well the PR I made will work in practice since the only platform packaged is gnome and the only styles are for gnome. If we get more of either it will need improvement.

**Comment by TingPing** [comment]
Well hopefully I figured out phabricator: https://phabricator.kde.org/D10675

**Comment by nedrichards** [comment]
Awesome! Glad that's progressing. So, to get back to the point of the issue - what's the best way to get this into flathub. Setup new git repos at KDE for each style and platform, then add automatic import here? Or just import and maintain the manifests directly in flathub?

**Comment by TingPing** [comment]
> Or just import and maintain the manifests directly in flathub?

Can't do that since they have multiple versions (5.9, 5.10) and there is no system in flathub to handle that yet.

**Comment by nedrichards** [comment]
Right, so it has to be separate repo per manifest and one version per
branch. Then add the details to buildbot to build automatically.

**Comment by ramcq** [comment]
So... we can totally build stuff from different git branches to different flatpak branches... it's how the runtimes themselves are built. https://github.com/flathub/buildbot-config/blob/master/builds.json#L20

**Comment by nedrichards** [comment]
OK, I've sent a PR to add the config that would build and add this automatically, same as the runtime and sdk. @grulja @aleixpol this is assuming that the flatpak-kde-applications repo gets a branch setup the same as the flatpak-kde-runtimes repo - but I think we'd need that anyway.

**Comment by grulja** [comment]
QGnomePlatform should be now available on Flathub, this can be closed.
