### ISSUE TITLE
Validate appdata *before* building

### ISSUE THREAD

**Issue by kparal** [flathub/buildbot-config#63]
Currently the project is built and only then the appdata file is verified. So if the check fails, like [here](https://flathub.org/builds/#/builders/21/builds/255), we've wasted a lot of computer and human time instead of providing an instant failure. Please provide a faster feedback loop and validate the appdata file as soon as possible.

**Comment by TingPing** [comment]
Bit impossible really. It can make hacky assumptions but at the end of the day the state required to check if the appdata is truely valid only exists after building.

**Comment by kparal** [comment]
Hmm, I was having the assumption that the appdata file is already in the git repository, because that's my case. In that case it's easy to find and check. But it's true that if the appdata file is part of the upstream tarball, which is the preferred approach anyway, then it would be quite hard to do the check beforehand. Sorry for bothering, closing.
